### ISSUE TITLE
Erro na agenda das singles

### ISSUE THREAD

**Issue by leogermani** [hacklabr/mapasculturais#1101]
ver imagem

![7e8648ec-e958-11e6-8022-1b07f9512df7](https://cloud.githubusercontent.com/assets/971483/22735633/b8235be8-ede1-11e6-9bb0-b00370cb4d31.png)

**Comment by rafaelchavesfreitas** [comment]
não consegui reproduzir e neste outro projeto da mesma instalação não acontece
http://culturaenlinea.uy/projeto/112/#tab=agenda

**Comment by leogermani** [comment]
Consegui reproduzir.

É preciso estar logado como usuário não admin. Acontece tb na single do espaço e do agente dono do evento.

O agente que criou o evento é um agente coletivo. E o evento foi criado por outro agente com controle sobre o agente que assina o evento.
