### ISSUE TITLE
Erro de permissão ao tentar se inscrever em edital

### ISSUE THREAD

**Issue by leogermani** [hacklabr/mapasculturais#1103]
Em alguns casos, que não consegui perceber qual é o padrão, ocorre um erro javascript ao se tentar registar em um edital. (Este é um problema, não consigo descrever como chegar a esta situação, mas tenho uma base aqui que acontece e posso dizer que tem acontecido muitas vezes)

```
Error: $scope.data.entity.registrations[i].owner is null
```
Este erro é disparado depois de selecionar o agente responsável e clicar em Inscrever-se. Aqui:

https://github.com/hacklabr/mapasculturais/blob/master/src/protected/application/themes/BaseV1/assets/js/ng.entity.module.project.js#L1088

Esse erro acontece porque um ou mais objetos da array MapasCulturais.entity.registrations tem a propriedade "owner" setada como null.

Investigando, vi que é algum problema de checagem de permissão... e acontece aqui:

https://github.com/hacklabr/mapasculturais/blob/master/src/protected/application/lib/MapasCulturais/Entities/Registration.php#L202

É preciso ou modificar alguma coisa nesta checagem, ou modificar a maneira como a página é montada para evitar esse erro.

Se quiser me indicar o caminho de como corrigir, posso fazer. Só não sei realmente qual é o comportamento esperado.

**Comment by rafaelchavesfreitas** [comment]
Pode verificar se por acaso o status do agente padrão do usuário que está tentando se inscrever está como rascunho?
