### ISSUE TITLE
Tabela exportada de eventos deveria ter os dados do ONDE: bairro, cidade, e respectivos dos shapefiles

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#1165]
ao exportar uma tabela de eventos é importante ter além do ONDE (link do perfil de espaço) dados sobre bairro, e referentes aos shapes: isso facilita na pesquisa e análise da tabelal exportada.

**Comment by leogermani** [comment]
Pessoal, 

Aqui acho que vale uma mudança grande.

Hoje a planilha tem alguns problemas para ser trabalhadas

ex:

1. o link para o espaço vem na mesma célula da ocorrência, não dá pra filtrar por espaço.. Além de botar o espaço em uma coluna separada, poderíamos botar infos da localização do espaço em colunas também. Fundamental poder filtrar por localização...

2. existem células mescladas, o q tb dificulta ordenação e filtros..

Nâo seria melhor mesmo normalizar tudo. Botar uma ocorrência por linha, mesmo que fique m repetidas as informações do evento várias vezes?

Coloco aqui duas planilhas pra exemplificar uma proposta. Neste zip a planilha original é um exemplo de como ela é exportada hoje. A proposta traz os mesmos dados, apenas dos 3 primeiros eventos, no formato normalizado.

[planilhas-eventos.zip](https://github.com/hacklabr/mapasculturais/files/1061087/planilhas-eventos.zip)

**Comment by Andreqlp** [comment]
uma demanda semelhante de detalhamento de endereço na entidade projetos (exportar inscrições): https://github.com/secultce/mapasculturais/issues/15

**Comment by Andreqlp** [comment]
Outra proposta para exportação dos dados.

 Utilizei como base o padrão entrada de informação e nomenclatura que está no mapas. Para evitar caracteres estranhos no título, optei pela retirada dos acentos.

[Uploading mapas-culturais-dados-exportados-outra-proposta.ods…]()

**Comment by donsalvatore** [comment]
Olá galera!
sobre a questão evento x ocorrência.
Acabei de fazer um teste na instalação SaaS do Maranhão: ma.mapas.cultura.gov.br/
é um projeto do São João onde existem arraiais e os Bois (bumba-meu-boi) circulam neles. Ou seja, cada apresentação é um evento porém na lógica da plataforma vc deve
1 - título do evento: nome do Boi
2 - ocorrência diversas nos diversos arraiais

isso faz com que a contagem de eventos seja 1, num boi que na verdade realizou mais de 5 apresentações (eventos), e que o sistema chama de ocorrência.

Isso de algum modo devia:
.estar explícito para o gestor na plataforma online.
.na tabela que se exporta é possível contar as ocorrência (OK demais!!) porém existe os seguinte problemas como se ode ver na tabela anexa:
a) na coluna ocorrência existe essa info: Dia 14 de junho de 2017 às 19:00, Arraial da Maria Aragão livre 
horário, data, valor e local estão na mesma célula. Isso é ruim para filtragens e estudos

aqui o link do projeto: http://ma.mapas.cultura.gov.br/projeto/295/#tab=agenda




[mapas-culturais-dados-exportados.pdf](https://github.com/hacklabr/mapasculturais/files/1092879/mapas-culturais-dados-exportados.pdf)

**Comment by leogermani** [comment]
@donsalvatore se vc olhar a proposta do Jedi, ela já resolve essa coisa de separar as infos que estão todas numa mesma célula.

Em relação a contagem, podemos tentar colocar as duas. Mas vc sugere uma maneira de escrever isso?

1 evento e 5 ocorrências encontradas?

**Comment by donsalvatore** [comment]
não consegui terminar esse mail mas ...



Pensei aqui!

A tabela que mandei já evidencia nas linhas a quantidade de ocorrência.
O que você me coloca é pensar como, online/no mapa, a info seria
apresentada.

Pois é! Pensei que acho massa discutir isso com o povo da antologia, eu
topo. Porque talvez como o mapa está agora dividido não permitiria um
avanço na terminologia.

O Projeto como agregador de eventos e editais é mto bom ter. E ele permite
ser categorizado como festival, encontro, projeto (falta colocar essa e tb
inscrições)

Abaixo disso complica porque vejo alguns padrões e podemos começar por aí
pra pensar:

.Um festival de Rock com "n" bandas
O que são as bandas? Eventos com 1 ocorrência? Acho que evento não é mas 1
ocorrência sim é. Talvez posso ser chamada tb de atração.

. Um ciclo de debate
O que são as mesas? Atrações? Não seria tofo o ciclo um evento?!

e por aí vai

Miguel Gondim de Castro
+55 11 971612502 <(11)%2097161-2502>

Em 23 de jun de 2017, às 13:10, leogermani <notifications@github.com>
escreveu:

@donsalvatore <https://github.com/donsalvatore> se vc olhar a proposta do
Jedi, ela já resolve essa coisa de separar as infos que estão todas numa
mesma célula.

Em relação a contagem, podemos tentar colocar as duas. Mas vc sugere uma
maneira de escrever isso?

1 evento e 5 ocorrências encontradas?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hacklabr/mapasculturais/issues/1165#issuecomment-310707519>,
or mute the thread
