### ISSUE TITLE
Problemas com links a partir da planilha no Excel

### ISSUE THREAD

**Issue by leogermani** [hacklabr/mapasculturais#1204]
Excel e outras aplicações do Office verificam o link clicado antes de levar o usuário para aquela página. Esse "comportamento" é para ver se o link é para outro documento office que seria aberto na aplicação, e não no navegador.

Detalhes em: http://stackoverflow.com/questions/2653626/why-are-cookies-unrecognized-when-a-link-is-clicked-from-an-external-source-i-e

O problema é que ao fazer essa verificação, ele não está levando em conta os cookies do navegador. Então se o link aponta para uma página que requer autenticação no Mapas, o que ele vai retornar é o link para a página de autenticação (pq o mapas redireciona aquela requisição).

Então o usuário tem a experiência de clicar em um link e cair na página de autenticação, mesmo já estando logado. E ainda por cima, perde o redirect_to, então ele simplesmente não vai para o link que deveria ir.

Isso foi percebido na planilha de inscritos em uma chamada, que traz um link para a Inscrição. Porém esse link fica inacessível a partir do excel.

SOLUÇÕES POSSÍVEIS:

1) Na planilha exportada, não colocar o link em uma tag A clicável. Colocar o link todo em uma coluna, que a pessoa tenha q copiar e colar no navegador.

2) Colocar uma verificação de user agent no Mapas, que verifica se a requisição tá vindo do Office, e aí não redireciona ele imediatamente pra autenticação, de maneira que ele leve o usuário pro lugar certo.

Essa abordagem está descrita aqui: https://github.com/spilliton/fix_microsoft_links/blob/master/lib/fix_microsoft_links.rb

O caminho 1 é mais simples. O caminho 2 tem que avaliar.

**Comment by Andreqlp** [comment]
Oi Léo, não enfrentamos esse problema, pois estamos trabalhando no drive e o link direciona já para a inscrição, caso o usuário esteja logado no mapas. De todo modo, acho que a solução 1 é a ideal. Uma boas práticas das tabelas de dados é ter uma informação única por coluna,assim seria uma para o número de inscrição e outra com o link.
