### ISSUE TITLE
Problemas ao encontrar os arquivos .JS

### ISSUE THREAD

**Issue by renatobsd** [hacklabr/mapasculturais#1212]
Boa tarde,
Estou com dificuldades para botar o sistema em questão no ar. Aparentemente ele só esta compilando os .css e ignorando os .js. Segui a risca como menciona o guia de instalação e acredito que não há nenhum tipo de pacote faltando.

Erro:

vendor-5cabcf35ad7d76ee35f68723f48d9ba2.js Failed to load resource: the server responded with a status of 404 (Not Found)
app-7a455fdb56a56a1c8dc5408c603ad3ef.js Failed to load resource: the server responded with a status of 404 (Not Found)
vendor-5cabcf35ad7d76ee35f68723f48d9ba2.js Failed to load resource: the server responded with a status of 404 (Not Found)
app-7a455fdb56a56a1c8dc5408c603ad3ef.js Failed to load resource: the server responded with a status of 404 (Not Found)

Servidor: Ubuntu Server 16.04.2
PHP: 7

Obrigado.

**Comment by leogermani** [comment]
@renatobsd você verificou se esses arquivos estão sendo cirados no sistema de arquivos?

Dá uma mexida nas opções no config.php que tem relação com Assets. Assets cache, path e coisas assim...

@GustavoVS @rafaelchavesfreitas podem dar alguma orientação a mais?

**Comment by leogermani** [comment]
Vou fechar essa issue por falta de resposta. @renatobsd , para suporte entre em chat.mapasculturais.org
