### ISSUE TITLE
Ferramentas de gestao colaborativa

### ISSUE THREAD

**Issue by caleol** [hacklabr/mapasculturais#1250]
Boa tarde galera, sou da [UNIVESP ](https://univesp.br/), iniciamos uma pesquisa relacionada a ferramentas de gestão colaborativa e estamos conversando com alguns desenvolvedores e colaboradores que atuam na área, vocês podem nos ajudar ?

grato,

**Comment by leogermani** [comment]
Oi, claro,

Entra no nosso canal do telegram (tem o link no ícone no começo do README do repositorio) ou no nosso chat de desenvolvedores (link também no README, na seção Canais de Comunicação).

abraos

**Comment by caleol** [comment]
grato @leogermani
