### ISSUE TITLE
Habilitar opção de descrição para fotos da galeria

### ISSUE THREAD

**Issue by leogermani** [hacklabr/mapasculturais#1251]
Na galeria, habilitar opção de descrição para poder se utilizar para créditos, fonte ou qq outra finalidade

**Comment by Andreqlp** [comment]
ta rolando \o/

**Comment by valessiobrito** [comment]
Isso é uma questão de acessibilidade também.  Já esta rolando? Qual versão?

**Comment by leogermani** [comment]
https://github.com/hacklabr/mapasculturais/blob/develop/documentation/changelogs/3.2.md
