### ISSUE TITLE
O texto com a escala das notas está mostrando o código <br>

### ISSUE THREAD

**Issue by Andreqlp** [hacklabr/mapasculturais#1261]
O texto que aparece quando se passa o mouse em cima das notas.

![mapa_descricao com codigo](https://user-images.githubusercontent.com/14170372/28214157-8579a206-687f-11e7-9e2a-651d904c2314.png)

**Comment by rafaelchavesfreitas** [comment]
É para aparecer um tooltip como este:
![Screenshot from 2017-07-25 19-00-38.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53766f08ebef97b1f959d8f3/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227e49f37c3dd7b668ee1b36515f424da453444d04bea6d37ef5f22e7a985908edd46f5922953e40a9bc8119ea54eb72df1dd1b1eddf5edcfa7f74b9dfd0126754505a9bf54f37a6934acd58f74be0445cac143462ee647b.png)

@Andreqlp verifica se não houve algum erro de javascript por favor.

**Comment by Andreqlp** [comment]
funcionando
