### ISSUE TITLE
fatiamento de inscrições entre os avaliadores

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [hacklabr/mapasculturais#1263]
- [x] por número de inscrição
- [x] por categoria da inscrição

**Comment by Andreqlp** [comment]
Vi o novo módulo, mas não consegui testar por conta do erro reportado no #1066 

Modificar o nome dessa funcionalidade para Distribuição ao invés de Fatiamento. O texto de descrição ficaria assim:

> Utilize os campos de distribuição se quiser dividir as inscrições entre os avaliadores. Você pode definir um intervalo de inscrições para cada avaliador e/ou dividir as inscrições pela categoria definida no formulário.
> 
> No primeiro campo de distribuição informe o final do número de inscrição, de acordo com os exemplos abaixo.
> 
> 00-09 - para as inscrições com final entre 0 e 9
> 10-60 - para as inscrições com final entre 10 e 60
> 61-99 - para as inscrições com final entre 61 e 99
> 
> No segundo campo do distribuição informe a(s) categoria(s) de inscrição.

O que aconte se o usuário deixar esses campos em branco?
