### ISSUE TITLE
É preciso permitir a edição da ficha de inscrição enquanto todas as inscrições ainda estão em rascunho.

### ISSUE THREAD

**Issue by Andreqlp** [hacklabr/mapasculturais#1270]
Depois de criar um questionário (principalmente um questionário complexo como o de um edital) é preciso testá-lo. A melhor forma de fazer isso é simulando uma inscrição, contudo o novo modelo exclui essa possibilidade. Minha sugestão é que seja possível editar o formulário enquanto todas as inscrições estiverem como rascunho.

![erro-permitir modificar se so tiverem rascunhos](https://user-images.githubusercontent.com/14170372/28447802-a2e2147a-6da9-11e7-96df-edd4bb134b07.png)

**Comment by rafaelchavesfreitas** [comment]
adicionei possibilidade de pré-visualizar a ficha de inscrição

**Comment by Andreqlp** [comment]
Achei bem bacana o botão de testar o formulário, só é preciso fazer alguns ajustes na configuração dessa nova janela:

1) Substituir o botão de salvar por fechar
2) Retirar a opção de salvar automaticamente
3) não perguntar se quer salvar quando sair

![botao salvar na pre-visualizacao](https://user-images.githubusercontent.com/14170372/28630001-6c4eee9c-71ff-11e7-9d5c-e00aa5329a9b.png)
![erro-questrionaro teste sair](https://user-images.githubusercontent.com/14170372/28630015-73550564-71ff-11e7-88f5-29ca389b33bc.png)
