### ISSUE TITLE
Não aparece as respostas da ficha de inscrição

### ISSUE THREAD

**Issue by Andreqlp** [hacklabr/mapasculturais#1311]
Foi um erro relatado pelo Marcus do MINC e que vc também tinha me alertado. Agora não lembro desse erro ter acontecido anteriormente, mas agora está aparecendo.

Aparece "campo não informado” nas respostas dos proponentes.
http://dev-mapa.cultura.ce.gov.br/inscricao/48705245/

![01](https://user-images.githubusercontent.com/14170372/33135814-44b2b2f2-cf82-11e7-9e65-01e43e3c4c97.png)

**Comment by rafaelchavesfreitas** [comment]
por favor testar com uma nova inscrição

**Comment by Andreqlp** [comment]
Criei uma nova oportunidade e continua sem aparecer a informação da inscrição:

Pagina de avaliação: http://dev-mapa.cultura.ce.gov.br/inscricao/1485769430/
Perfil do avaliador: http://dev-mapa.cultura.ce.gov.br/agente/6455/

![02_continua sem apresenartar os campos de informacao](https://user-images.githubusercontent.com/14170372/33887952-46e10dfa-df2a-11e7-8ca9-075cbd636da5.jpg)

**Comment by Andreqlp** [comment]
O problema de não exibir o campo de informação para o avaliador permanece.

Nova oportunidade criada: http://dev-mapa.cultura.ce.gov.br:8001/oportunidade/780
Perfil do avaliador: http://dev-mapa.cultura.ce.gov.br:8001/agente/16010/
Inscrição de exemplo: http://dev-mapa.cultura.ce.gov.br:8001/inscricao/40910161/

![03 aparecendo como campo nao informado](https://user-images.githubusercontent.com/14170372/34259316-9aff80e8-e640-11e7-86e7-30a6a65e0ed0.png)

**Comment by Andreqlp** [comment]
Agora foi
