### ISSUE TITLE
Não está mudando o status da avaliação no painel coordenador

### ISSUE THREAD

**Issue by Andreqlp** [hacklabr/mapasculturais#1312]
Mesmo depois de enviar as avaliações o status continua com pendente para o coordenador, mas se pedir para “baixar lista de avaliações” aparece tudo.

Oportunidade: http://dev-mapa.cultura.ce.gov.br/oportunidade/771/#tab=evaluations 

![02](https://user-images.githubusercontent.com/14170372/33136038-ef4b061a-cf82-11e7-8097-e745b4d60833.png)

**Comment by Andreqlp** [comment]
Como não aparecem informações na aba de avaliações, o coordenador do projeto não consegue acessar os pareceres de cada avaliador.

**Comment by rafaelchavesfreitas** [comment]
fiz algumas alterações que podem ter corrigido o problema

**Comment by Andreqlp** [comment]
Ainda não está rankeando. 

Novo projeto criado: http://dev-mapa.cultura.ce.gov.br:8001/oportunidade/790/#tab=inscritos

![ainda nao rankeia](https://user-images.githubusercontent.com/14170372/34728019-6be3b27e-f537-11e7-9a40-b089f7f8cd36.png)

**Comment by Andreqlp** [comment]
Continua sem aparecer.

Projeto que testei: http://dev-mapa.cultura.ce.gov.br:8001/oportunidade/790/#tab=evaluations

**Comment by Andreqlp** [comment]
Acabei de perceber que no painel do Superadmin aparece tudo direitinho, mas a mesma informação não aparece no painel do gerente do projeto.

Tela do superadmin:
![paneil superadmin](https://user-images.githubusercontent.com/14170372/35161393-d69c78dc-fd1e-11e7-918e-0bbc746e6504.png)

Tela do gerente do projeto:
![geremte dp rpk](https://user-images.githubusercontent.com/14170372/35161400-dd7532c0-fd1e-11e7-9d2d-956e235ecb7c.png)

**Comment by Andreqlp** [comment]
resolvido
