### ISSUE TITLE
Criei uma terceira fase, mas não foi possível importar os inscritos

### ISSUE THREAD

**Issue by Andreqlp** [hacklabr/mapasculturais#1314]
O botão de importar as inscrições não funciona e quanto tentei clicar pela segunda vez apareceu a seguinte mensagem de erro:
{"error":true,"data":"As inscri\u00e7\u00f5es j\u00e1 foram importadas para esta fase"}
http://dev-mapa.cultura.ce.gov.br/oportunidades/importLastPhaseRegistrations/sent:1/769/

Oportunidade: http://dev-mapa.cultura.ce.gov.br/oportunidade/769/#tab=inscritos 

![05](https://user-images.githubusercontent.com/14170372/33136185-64e21a80-cf83-11e7-806f-3b8b1da9446a.png)

**Comment by rafaelchavesfreitas** [comment]
na verdade os inscritos tinahm sido importados. tinha um erro na api que retornava as inscrições da fase a partir da terceira fase

**Comment by Andreqlp** [comment]
deu certo agora
