### ISSUE TITLE
Link API quebrado

### ISSUE THREAD

**Issue by grayce1220** [hacklabr/mapasculturais#1323]
O link da API está quebrado https://github.com/hacklabr/mapasculturais/blob/master/doc/api.md . Podem verificar, por favor?

**Comment by Andreqlp** [comment]
aqui tem algumas informações sobre a api: http://docs.mapasculturais.org/mc_config_api/

**Comment by leogermani** [comment]
o link que estava na página padrão da home foi corrigido
