### ISSUE TITLE
As inscrições deixaram de aparecer para o gerente na Avaliação Simplificada

### ISSUE THREAD

**Issue by Andreqlp** [hacklabr/mapasculturais#1330]
Criei uma nova fase do tipo Avaliação Simplificada e consegui fazer a importação das inscrições de uma fase passada normalmente. Na primeira vez consegui visualizar as inscrições normalmente, mas depois que foi realizada a avaliação, as inscrições sumiram do painel o gerente.

Perfil do Gerente: http://dev-mapa.cultura.ce.gov.br/agente/16010/
Perfil do Avaliador: http://dev-mapa.cultura.ce.gov.br/agente/6690/
Oportunidade: http://dev-mapa.cultura.ce.gov.br/oportunidade/778/#tab=inscritos

Imagem da aba inscrições do gerente:
![07-gerente da oportuniade](https://user-images.githubusercontent.com/14170372/33894178-13ef5138-df3c-11e7-8200-edb568cb1fa6.png)

Imagem da aba avaliações do avaliador:
![07-hab juridica as inscricoes so aparecem para o avaliadir](https://user-images.githubusercontent.com/14170372/33894184-1a161bdc-df3c-11e7-8294-623a8e730c46.png)

**Comment by rafaelchavesfreitas** [comment]
o problema não era causado pelo método de avaliação, mas sim pela confusão com as datas de término de inscrição de cada fase.

**Comment by Andreqlp** [comment]
entendi, então o importante é a data de finalização e não o horário
