### ISSUE TITLE
Apareceu um erro quando tentei acessar as avaliações depois do resultado publicado

### ISSUE THREAD

**Issue by Andreqlp** [hacklabr/mapasculturais#1332]
Após a publicação do resultado apareceu esse erro quando teitei acessar a inscrição, tanto para o gerente do projeto quanto para o avaliador. Estranho é que algumas vezes consegui acessar e outras vezes apareceu o erro:

Projeto: http://dev-mapa.cultura.ce.gov.br:8001/oportunidade/788/

![01 erro ao tentar modificar inscricao que nao foi enviada e publicado o resultado](https://user-images.githubusercontent.com/14170372/34445983-6ea3fb2e-ecb6-11e7-9972-f15ddac4c1e2.png)

**Comment by rafaelchavesfreitas** [comment]
não consegui reproduzir. vou precisar de um novo dump do ambiente de teste para tentar reproduzir localmente.

**Comment by Andreqlp** [comment]
Estou entrando pelo endereço sem a indicação da porta e o erro não apareceu mais.
