### ISSUE TITLE
Opção de reposicionar o banner (imagem) de um equipamento

### ISSUE THREAD

**Issue by valessiobrito** [hacklabr/mapasculturais#1340]
Como usuário, ao definir a imagem do topo (banner), possibilitar editar/reposicionar.   

Similar como outras redes (twitter, facebook, g+) permite fazer com o tipo de imagem/banner do perfil.

**Comment by leogermani** [comment]
@valessiobrito Isso já foi implementado há um tempo. Talvez vocês precisem atualizar o ambiente de vocês!
