### ISSUE TITLE
campo "Nome do Projeto" não está aparecendo para o avaliador

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [hacklabr/mapasculturais#1342]

**Comment by r-guimaraes** [comment]
@rafaelchavesfreitas Poderia dar mais detalhes dessa issue por favor?

**Comment by Andreqlp** [comment]
Quando você seleciona o "Campo do Nome do Projeto" no formulário de inscrição de uma oportunidade com opcional ou obrigatório, é criado um novo campo para ser preenchido no formulário de inscrição. Contudo esse campo não aparece posteriormente para o Avaliador dessa inscrição.

Esse é o campo::
![01 campo nome do projeto](https://user-images.githubusercontent.com/14170372/37101706-fd17ef18-2204-11e8-9ab3-dfbb748c47aa.png)

**Comment by r-guimaraes** [comment]
Feito
