### ISSUE TITLE
o upload de arquivo parece não funcionar se clicado mais de uma vez numa internet lenta

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [hacklabr/mapasculturais#1357]

**Comment by rafaelchavesfreitas** [comment]
a barra de progresso cresce e diminui freneticamente.

**Comment by cintiansilva** [comment]
Isso pode afetar  o upload de arquivos em inscrições de editais?

**Comment by leogermani** [comment]
Afeta sim,

Solução proposta: desabilitar o botão de enviar anexo depois que já tiver clicado a primeira vez. e/ou verificar no callback se o upload já está em andamento

**Comment by r-guimaraes** [comment]
Commit dessa issue aqui (https://github.com/culturagovbr/mapasculturais/commit/96e7d69874cfd4be68e22c5d23ecf6aa536428b8) 
na branch develop

**Comment by leogermani** [comment]
@rafaelchavesfreitas consegue validar? tá no pull request https://github.com/hacklabr/mapasculturais/pull/1369 que já está vindo com outras coisas tb, mas é o último commit lá
