### ISSUE TITLE
SINGLES header + imagem avatar - quais as dimensões (explicar ou poder editar online)

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#159]
De algum modo poder editar online a imagem ou especificar para o usuário as dimenções e tamanho da image.

**Comment by belisards** [comment]
seria uma boa esta mensagem, 
pelo que vi aqui, o tamanho dela é 812 x 192 , certo?

**Comment by leogermani** [comment]
Acredito q a funcionalidade de recortar essas imagens já deu conta disso.
