### ISSUE TITLE
Responsivo: Finalizar os estilos responsivos

### ISSUE THREAD

**Issue by catkit** [hacklabr/mapasculturais#215]
Essa é uma tarefa grande que precisa ser terminada e provavelmente necessitará java script.

**Comment by catkit** [comment]
Acho que o slimscroll não funciona com touch, ou seja em tablets e celulares

**Comment by catkit** [comment]
Falta tbm:
- [ ] verificar todas as tabelas das inscrições e colocar mensagem quando não aparece;
- [ ] alert com botão de fechar;
- [ ] estilos das agendas das singles;
- [ ] abas das singles de projetos;
- [ ] alerts da editable-entity no responsivo;
- [ ]  .dono na single;
- [ ]  ocultar botão adicionar sub-espaço nas telas menores que $screen-tablet (single espaço);
- [ ]  selo 'verificada'  quando sidebars ficam embaixo do main-content;
- [ ] botões de compartilhar quando sidebars ficam embaixo do main-content;
- [ ] ocultar botões de adicionar no submenu do .session-menu  em telas menores que $screen-tablet;
- [ ] galerias de imagens e vídeos;

**Comment by ariadnemelo** [comment]
iPhone (320x568)
- [ ] tirar transition das abas 

iPad (1024x768) modo retrato
- [ ] corrigir botão de adicionar grupo de agente
