### ISSUE TITLE
Recuperação de Senha não funcionou com mail da prefeitura

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#408]
Olá, Miguel. Boa tarde.

Preciso recuperar o meu Login e Senha da SP Cultura.

Já fiz os procedimentos do site, mas sem sucesso.

PS. O e-mail que eu tenho cadastrado é o da prefeitura.

Abs,

Cleber

**Comment by rafaelchavesfreitas** [comment]
relacionado com https://github.com/hacklabr/mapasculturais-openid
