### ISSUE TITLE
Single do agente :: espaços do agente vir em ordem alfabética e, se possível, com um campo de busca

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#449]
agntes como a SMC ou SMB possuem muitos espaços... a ordem alfabética ajudaria muita a busca e se possível (apenas se possível) uma busca quando um espaço tiver mais de x espaços.....

**Comment by marylly** [comment]
@ariadnemelo, poderia testar esta situação, por gentileza?
