### ISSUE TITLE
troca de senha - deposi de logado não hea como acessar essa página http://id.spcultura.prefeitura.sp.gov.br/accounts/password/change/

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#455]
colocar no painel um caminho para http://id.spcultura.prefeitura.sp.gov.br/accounts/password/change/ ou para a tela meu perfil

**Comment by rafaelchavesfreitas** [comment]
relacionado ao projeto https://github.com/hacklabr/mapasculturais-openid
