### ISSUE TITLE
CAMPO DE ENDEREÇO :: SINGLE AGENTE E ESPAÇO

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#479]
Atualemente o endereço é composto por um camp genérico que faz as busca do endereço, zona, distrito e subprefeitura.

Sugerimos (eu + SMC) após experiência do edital que utilizou o spcultura que esteja escrito ENDEREÇO COMPLETO sem que os demais campos (zona, distrito e subprefeitura) estejam visíveis. Ao salvar eles aparecem. Isso pq a pessoa acaba resumindo o endereço pq vê os campso abaixo e várias endereços começam a surgir fora da zona de sp.

**Comment by leandrodb** [comment]
@donsalvatore fizemos tudo? Sugiro ler esta issue no [github](https://github.com/hacklabr/mapasculturais/issues/479). Reflito se faz sentido ainda modificar o label do campo para "endereço completo". Mas as zonas subprefeituras estão ok?

**Comment by donsalvatore** [comment]
opa!!! no devel e no spcultura ainda constam as 3 opções para agente: não informar / aproximado / preciso.
