### ISSUE TITLE
primeiro log, um mail poderia ser enviado com log e senha

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#499]
"Miguel,

Sabe o que eu pensei?
Quando a pessoa se cadastrar no SPCultura, tem como o sistema enviar um e-mail para a pessoa confirmando o cadastro dela e com o nome de login e senha?
Por exemplo, a Natália voltou a trabalhar com a gente, mas na hora de resgatar logine senha dela, ela não lembrou. E não tem nenhum e-mail guardado com essa informação.
Entendeu?
Rola?
beijo"

**Comment by marylly** [comment]
Isso foi contemplado na issue #916.
Encerrando esta issue @donsalvatore.
