### ISSUE TITLE
exportação de tabelas exemplo Virada - erro

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#507]
isso aparece na tela
The webpage at http://spcultura.prefeitura.sp.gov.br/api/event/findByLocation/?@select=id,singleUrl,name,shortDescription,terms,classificacaoEtaria,project.name,project.singleUrl,occurrences&@keyword=virada%20cultural&isVerified=EQ(true)&@from=2014-05-17&@to=2014-05-18&@order=name%20ASC&@type=excel might be temporarily down or it may have moved permanently to a new web address.
Error code: ERR_INVALID_RESPONSE

**Comment by rafaelchavesfreitas** [comment]
isto deve ter relação com o tempo de resposta da api
