### ISSUE TITLE
HOME destaques - fotos de baixa resolução "enfeiam o sistema" apenas em agentes, espaços e projetos

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#508]
Na home - agentes, espaços e projetos
destaques tem definição de imagem muito ruim em comparação com os eventos.
eles puxam a foto do avatar né? se sim, de fato seria melhor apenas se tiver na galeria pq fica feião...

**Comment by catkit** [comment]
Relacionada #627
