### ISSUE TITLE
ERRO BIZARRO COM OCORÊNCIA :: datas malucas abaixo exemplo

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#514]
Selecionoi a data 19 de outubro, domingo. O sisteam teima em colocar na linha debaixo dia 18. tentei inúmeras vezes e isso se repitiu apenas com essa data...????? ???? perigoso se se repete

![bizarro](https://cloud.githubusercontent.com/assets/2921891/4664246/7ac3b1a6-5542-11e4-9c65-b7593b94d8f9.jpg)

**Comment by rafaelchavesfreitas** [comment]
este erro não acontece
