### ISSUE TITLE
NOTIFICAÇÕES :: FATAL ERROR

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#519]
ao rejietar uma notificação (que aliás não desaparece ao clicar) a seguinte tela:
Fatal error: Call to a member function delete() on a non-object in /home/hacklab/repository/mapasculturais/src/protected/application/lib/MapasCulturais/Entities/RequestAgentRelation.php on line 39

correpondente a seguinte URL: http://spcultura.prefeitura.sp.gov.br/rejeitar-notificacao/2761/

**Comment by rafaelchavesfreitas** [comment]
já foi resolvido
