### ISSUE TITLE
Buscar endereços com OSM Nominatim

### ISSUE THREAD

**Issue by leandrodb** [hacklabr/mapasculturais#528]
Além de a ferramenta ser aberta e podermos instalar em nosso servidor ou usar online, achei bem mais fácil de fazer um exemplo de chamada com restrição de área. Por exemplo essa chamando av brasil restringindo à área de são paulo
http://nominatim.openstreetmap.org/search?format=html&q=av%20brasil&xhr=1&bounded=1&polygon=0&viewbox=-46.75575256347656,-23.572955615696255,-46.58134460449219,-23.50355189742412

O format pode ser modificado de html para json no url. No formato html, não adianta testar outros endereços digitando no input, senão ele remove a área de restrição que configurei. Precisa ser modificado diretamente na url.

Documentação aqui: http://wiki.openstreetmap.org/wiki/Nominatim

**Comment by leogermani** [comment]
Foi modificada essa implementação. Ver https://github.com/hacklabr/mapasculturais/blob/develop/documentation/docs/mc_developer_geocoding.md
