### ISSUE TITLE
implementar validações dos agentes das inscrições

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [hacklabr/mapasculturais#536]
- agente responsável é obrigatório deve ser do tipo individual e ter CPF cadastrado
- instituição responsável PODE SER obrigatório,  deve ser do tipo coletivo e ter CNPJ cadastrado
- coletivo PODE SER obrigatório, deve ser do tipo coletivo sem obrigatoriedade de CNPJ

mas isto só para enviar a inscrição. acho que ok poder definir os agentes errados no backend se este não deixar enviar a inscrição se eles não estiverem corretos. Fazemos um filtro no frontend para só retornar os agentes do tipo coletivo para os agentes 2 e 3 e individual para o agente 1.

**Comment by donsalvatore** [comment]
ok... mas então vai rolar valido de CPF e CNPJ ou seja. Se escolher individual é CPF, se escolher coletivo é CNPJ. Obrigatórios apenas para quem se inscrever em editais.  é isso? e se for isso, fico apenas com a questão: micro empreendedor individual: ele é uma empresa e é um indivíduo.... durma com essa
