### ISSUE TITLE
Renomear aba Aprovados para Resultado

### ISSUE THREAD

**Issue by leandrodb** [hacklabr/mapasculturais#576]
Com lista de todos os inscritos ordenadas por status ou filtradas por aprovados

**Comment by donsalvatore** [comment]
fui aprovar um candidato em fomento a dança. aprovei e ao clicar em publicar resultados apareceu isso: 

Permission Denied: 
exception 'MapasCulturais\Exceptions\PermissionDenied' with message 'User with id 1 is trying to publishRegistrations the Project with the id 260' in /home/hacklab/repository/mapasculturais-devel/src/protected/application/lib/MapasCulturais/Entity.php:235
Stack trace:
#0 /home/hacklab/repository/mapasculturais-devel/src/protected/application/lib/MapasCulturais/Entities/Project.php(270): MapasCulturais\Entity->checkPermission('publishRegistra...')
#1 /home/hacklab/repository/mapasculturais-devel/src/protected/application/lib/MapasCulturais/Controllers/Project.php(46): MapasCulturais\Entities\Project->publishRegistrations()
#2 [internal function]: MapasCulturais\Controllers\Project->ALL_publish('260')
#3 /home/hacklab/repository/mapasculturais-devel/src/protected/application/lib/MapasCulturais/Controller.php(270): call_user_func_array(Array, Array)
#4 /home/hacklab/repository/mapasculturais-devel/src/protected/application/lib/MapasCulturais/RoutesManager.php(169): MapasCulturais\Controller->callAction('GET', 'publish', Array)
#5 /home/hacklab/repository/mapasculturais-devel/src/protected/application/lib/MapasCulturais/RoutesManager.php(107): MapasCulturais\RoutesManager->callAction(Object(MapasCulturais\Controllers\Project), 'publish', Array, false)
#6 [internal function]: MapasCulturais\RoutesManager->MapasCulturais\{closure}(Array)
#7 /home/hacklab/repository/mapasculturais-devel/src/protected/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#8 /home/hacklab/repository/mapasculturais-devel/src/protected/vendor/slim/slim/Slim/Slim.php(1338): Slim\Route->dispatch()
#9 /home/hacklab/repository/mapasculturais-devel/src/protected/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#10 /home/hacklab/repository/mapasculturais-devel/src/protected/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#11 /home/hacklab/repository/mapasculturais-devel/src/protected/application/lib/MapasCulturais/Middlewares/ErrorHandler.php(31): Slim\Middleware\MethodOverride->call()
#12 /home/hacklab/repository/mapasculturais-devel/src/protected/application/lib/MapasCulturais/Middlewares/ExecutionTime.php(44): MapasCulturais\Middlewares\ErrorHandler->call()
#13 /home/hacklab/repository/mapasculturais-devel/src/protected/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): MapasCulturais\Middlewares\ExecutionTime->call()
#14 /home/hacklab/repository/mapasculturais-devel/src/protected/vendor/slim/slim/Slim/Slim.php(1283): Slim\Middleware\PrettyExceptions->call()
#15 /home/hacklab/repository/mapasculturais-devel/src/protected/application/lib/MapasCulturais/App.php(375): Slim\Slim->run()
#16 /home/hacklab/repository/mapasculturais-devel/src/index.php(3): MapasCulturais\App->run()
#17 {main}
