### ISSUE TITLE
Corrigir top da div#capa-marca-dagua

### ISSUE THREAD

**Issue by catkit** [hacklabr/mapasculturais#601]
- [ ] Fazer aquela correção que foi feita na imagem do pingo da home do tema do RS no tema padrão.
- [ ] Fazer esse top ser calculado via js quando rola a página. Quando rola a página o top deve ser igual a zero.

**Comment by ariadnemelo** [comment]
@marylly fiz uma busca no projeto mas esse elemento `div#capa-marca-dagua`não existe em nenhum arquivo exceto no css já compilado do tema do RS, imagino que tenha sido retirado
