### ISSUE TITLE
Inscrições: Quando descrição do anexo é muito grande, conflita com botão de enviar modelo

### ISSUE THREAD

**Issue by leogermani** [hacklabr/mapasculturais#606]
COnforme screenshot

![screenshot from 2014-12-05 13 33 08](https://cloud.githubusercontent.com/assets/971483/5318010/7e97afae-7c83-11e4-9f05-fd7ac6a692d8.png)

**Comment by donsalvatore** [comment]
resolvido... mas no devel continua o erro conforme mail enviado

**Comment by donsalvatore** [comment]
no level ainda rola o problema

**Comment by rafaelchavesfreitas** [comment]
resolvido
