### ISSUE TITLE
refactor da localização e endereço dos agentes

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [hacklabr/mapasculturais#613]

**Comment by leandrodb** [comment]
- Retirar a opção de localização aproximada (será sempre precisa);
- Incluir opção de pública ou privada para a localização;
- Na excibição na single, mostrar ou esconder;
- Fazer um DB update para aproximado se tornar privado e preciso ser público;
- Filtrar na API mostrando apenas agentes com localização pública e somar aos "agentes sem localização" no mapa, mostrando apenas na lista;

**Comment by leandrodb** [comment]
Verificar com o @rafaelchavesfreitas porque existem [857 agentes aparecendo no mapa](http://spcultura.prefeitura.sp.gov.br/busca/##(global:(enabled:(agent:!t),filterEntity:agent))) e apenas [344 agentes com localização pública](http://spcultura.prefeitura.sp.gov.br/api/agent/find/?@select=id,name,location&publicLocation=EQ(true)&@type=html)
