### ISSUE TITLE
Responsivo: melhorar js dos submenus de usuário e notificações

### ISSUE THREAD

**Issue by catkit** [hacklabr/mapasculturais#617]
Fazer essa tarefa na branch issue-#215-responsivo.
Ao clicar nos elementos <a> que abrem os submenus, verificar se o outro submenu está aberto, se estiver, fechar para não ficarem sobrepostos.

**Comment by leandrodb** [comment]
Limpei as diferentes variáveis de escopo angular e criei um esquema de toggle padrão no mapasculturais.js. Para fixar a issue adicionei um evento que é executado uma única vez, ao clicar em qualquer alvo fora do elemento ele é escondido
