### ISSUE TITLE
Na single da inscrição colocar status e permitir alterar o status pra quem tem permissão

### ISSUE THREAD

**Issue by leogermani** [hacklabr/mapasculturais#621]

**Comment by catkit** [comment]
Design feito no commit 28fbbbd

**Comment by leandrodb** [comment]
Fiz para os owners do projeto, não aparece nada caso contrário.

**Comment by catkit** [comment]
@leandrodb eu esqueci das cores. Na tabela, dependendo do status selecionado, uma classe diferente é aplicada na `tr`, que faz mudar a cor do fundo, a borda esquerda e a cor do `.dropdown`. Aqui pensei de aplicar a classe no próprio `.dropdown`, você pode fazer isso? Já criei as classes no commit 9417182. São as seguintes:
- pendente - não precisa de classe, fica cinza mesmo.
- inválida - `.invalid`
- não selecionada - `.notapproved`
- suplente - `.waitlist`
- selecionada - `.approved`
- rascunho - não precisa de classe, pq volta a ficar editável.

**Comment by leandrodb** [comment]
@catikit, você viu que precisa alinhar o texto né?
