### ISSUE TITLE
Melhorar funcionamento do botão que mostra/esconde os filtros da busca avançada

### ISSUE THREAD

**Issue by catkit** [hacklabr/mapasculturais#626]
Nas telas com largura menor ou igual a 991px, dentro de cada div.entity-filter, aparece um header com um botão toggle que mostra/oculta todos os filtros.

- [ ] o botão deve mostrar/ocultar apenas os filtros da entidade selecionada.
- [ ] colocar uma animação no collapse.
- [x] verificar se após essas alterações, a programação que altera a margem do topo dinamicamente continua funcionando.

**Comment by leandrodb** [comment]
- [ ] resolver o bug quando a aba de filtros está aberta e se clica em um marcador abrindo o infobox, que aparece mal-posicionado...
