### ISSUE TITLE
Remover do html todas as classes do ElegantIcon

### ISSUE THREAD

**Issue by catkit** [hacklabr/mapasculturais#633]
Para facilitar a criação de temas e o uso de outras fontes de ícones, vamos:
- [x] remover todas as classes do Elegant Icon do html, substituindo por regras associadas aos estilos já existentes ou se for preciso, criando novas regras.
- [x] criar variáveis para o content e o caracter correspondente aos ícones desejados.

**Comment by ariadnemelo** [comment]
Fiz todas as alterações necessárias, ainda preciso testar mas seria bom se mais alguém testasse também

**Comment by catkit** [comment]
Dei uma conferida, precisa:
- [ ] renomear algumas variáveis e classes pra ficar mais semântico e usar apenas hífen ao invés de underline. Ex: $unicode-space ao invés de $unicode_building, .icon-space ao invés de .building
- [ ] comentar cada variável dizendo onde o ícone é usado.
- [ ] no .secondary-menu tem um ícone com a classe .info com a imagem de um círculo com um 'i' dentro . O ícone está certo, mas ficou azul, com a cor errada. Isso foi por causa da cor do ícone do .alert.info, mas o ícone de .alert.info não é esse, é uma lâmpada, está errado. Precisa ter duas classes diferentes, mantém a classe .info só pro alert com o ícone de uma lâmpada e cria uma pro .secondary-menu com o ícone do círculo com 'i' dentro, pode ser 'about';
- [ ] a variável $unicode_arrow_expand_alt3 não precisa, substituir pelo mixin arrow, aliás todas as setinhas que tiver com fonte é pra substituir pelo mixin (issue #565);
- [ ] na linha 183 do _registration-form.scss faltou substituir pela variável (ícone de download);
- [ ] na linha 20 do _dropdown.scss faltou substituir a variável (é a setinha pra baixo indicando que tem submenu, essa não será substituída pelo mixin);

**Comment by catkit** [comment]
- [ ] Remover o arquivo fonts.css em todo tema q usa ícones diferentes.
