### ISSUE TITLE
Home search dropdown-button hover bug

### ISSUE THREAD

**Issue by leandrodb** [hacklabr/mapasculturais#646]
Mudança do triângulo de ícone para mixin diminuiu o tamanho do elemento e agora causa evento de mouseout que esconde o submenu.

**Comment by leandrodb** [comment]
O mesmo erro acontece nos outros dropdowns

**Comment by donsalvatore** [comment]
não consegui tirar uma cópia de tela. Mas seguinte. na home, ao fazer uma busca o dropdown button tea com retângulo cinza envolta da opção eventos. Estranho né?

**Comment by leandrodb** [comment]
@donsalvatore, isto também é outra issue.

**Comment by leandrodb** [comment]
O bug do retângulo cinza o Miguel @donsalvatore  disse que não está mais ocorrendo. Vamos fechar esta issue.
