### ISSUE TITLE
Adicionar status da inscrição na lista de "minhas inscrições"

### ISSUE THREAD

**Issue by leandrodb** [hacklabr/mapasculturais#650]
somente enviado ou rascunho

**Comment by donsalvatore** [comment]
ok chequei e está ok... mas ante de passar para o teste o que significa isso na imagem (SINAL AZUL DE INTERROGAÇ˜AO) ... este em rascunho do agente 1 no devel

**Comment by leandrodb** [comment]
O que, Miguel? @donsalvatore

**Comment by donsalvatore** [comment]
opa. Perdão. Tá ok, vou abrir outra Issue sobre a questão e redigir melhor
