### ISSUE TITLE
Tornar Localização e Endereço Obrigatórios no Cadastro

### ISSUE THREAD

**Issue by leandrodb** [hacklabr/mapasculturais#658]
- Tanto para agentes quanto para espaços;
- Para suportar também espaços virtuais, além de físicos, criar um metadado ou tipo específico para isso. Por exemplo, pode ser nomeado 'natureza' e ter como possíveis valores 'físico' (padrão) e 'virtual'.

**Comment by leandrodb** [comment]
Afinal de contas é uma plataforma de mapeamento

**Comment by leandrodb** [comment]
@leogermani pode registrar um parecer sobre esta issue?

**Comment by leandrodb** [comment]
Fiz por enquanto para agentes. Miguel @donsalvatore, por favor, teste cadastrar e editar agentes.

**Comment by donsalvatore** [comment]
Ok!! O farei e dou feed

Enviado do meu iPhone

**Comment by donsalvatore** [comment]
acabei de testar consegui criar um agente sem
endereço no devel

Em 27 de janeiro de 2015 16:37, Donsalvatore <donsalvatore@gmail.com>
escreveu:

> Ok!! O farei e dou feed
>
> Enviado do meu iPhone
>
> Em 27/01/2015, às 15:14, Leandro Monteiro dal Bò <notifications@github.com>
> escreveu:
>
> Fiz por enquanto para agentes. Miguel @donsalvatore
> <https://github.com/donsalvatore>, por favor, teste cadastrar e editar
> agentes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hacklabr/mapasculturais/issues/658#issuecomment-71686766>
> .
>
>


-- 
Miguel de Castro Perez
http://about.me/migueldecastro
@serra_lheria
cel.: +55 11 97161 2502
