### ISSUE TITLE
Layout da edição de projeto, na aba inscrições, está zuado.

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [hacklabr/mapasculturais#662]
![1111](https://cloud.githubusercontent.com/assets/1181261/5859341/c690dbe0-a240-11e4-96fe-6881ca06e197.jpg)

**Comment by donsalvatore** [comment]
ainda tá zoado (testei no deve)

**Comment by rafaelchavesfreitas** [comment]
está resolvido
