### ISSUE TITLE
Sugestão na busca: mostrar ícone do selo de verificado na lista de filtros para diferenciar este filtro especial dos outros

### ISSUE THREAD

**Issue by leandrodb** [hacklabr/mapasculturais#665]

**Comment by leandrodb** [comment]
@catkit, só precisa você revisar este arquivo site/search.php. Coloquei um <span> com a classe .filter-verified (que copiei com alterações da class .btn-verified) para conter o ícone dentro das .tag-selected dos filtros de resultados verificados de cada entidade.

**Comment by catkit** [comment]
Acabei removendo porque no caso em que as cores do ícone são as mesmas das tags (mesmas das entidades) fica muito ruim a leitura, ex: Sobral.
