### ISSUE TITLE
Sobral: Divisões Geográficas / Shapefiles

### ISSUE THREAD

**Issue by leandrodb** [hacklabr/mapasculturais#674]
- [x] fazer o release copiando os arquivos sem git;
- [x] criar uma opção de configuração para o nível de simplificação dos polígonos;
- [x] corrigir a visualização do label e não da chave das geoDivision no controle de camadas do mapa;

**Comment by donsalvatore** [comment]
OBS:. faltam acentos nos nomes dos bairros
