### ISSUE TITLE
OpenID username duplicado - fatal error

### ISSUE THREAD

**Issue by leandrodb** [hacklabr/mapasculturais#675]
MultipleObjectsReturned at /accounts/login/
get() returned more than one User -- it returned 2!
Reproduzível com usuário 'leandro' com qualquer tentativa de senha.
Deve ter a ver com a migração para o openid novo

**Comment by leandrodb** [comment]
Quando peço com o usuário leandro@hacklab.com.br para redefinir senha, o email não chega como chega com leandro.db@gmail.com, que são os dois usuários com username iguais (leandro). Talvez os problemas estejam relacionados.

**Comment by rafaelchavesfreitas** [comment]
é deste projeto: https://github.com/hacklabr/mapasculturais-openid
