### ISSUE TITLE
em "minhas inscrições" (devel) ponto de interrogação azul

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#683]
esse ponto é algum erro?
![untitled](https://cloud.githubusercontent.com/assets/2921891/6110396/8429f3a0-b068-11e4-9880-082735004840.jpg)

**Comment by rafaelchavesfreitas** [comment]
no painel

**Comment by rafaelchavesfreitas** [comment]
por algum motivo a imagem de avatar do projeto estava quebrada
