### ISSUE TITLE
Busca de Eventos por palavra-chave busca eventos de projetos com esta palavra-chave, mas não traz eventos dos projetos-filho

### ISSUE THREAD

**Issue by leandrodb** [hacklabr/mapasculturais#687]
Miguel @donsalvatore reportou isto mostrando como exemplo o projeto Agente Comunitário (http://spcultura.prefeitura.sp.gov.br/projeto/152) que tem sub-projetos com eventos e ele queria que digitando agente comunitário na busca principal aparecesse a agenda de todos os subprojetos, como acontece na agenda da single do próprio projeto)

**Comment by donsalvatore** [comment]
Grato Leandro.
Isso é uma visualização importante por conta dos editais que vão se
multiplicar. Sem isso a função do mapa deixa de ter relevância e a análise
territorial dos fomentos (que são importantes) perde o uso da ferramenta


Em 10 de fevereiro de 2015 18:02, Leandro Monteiro dal Bò <
notifications@github.com> escreveu:

> Miguel @donsalvatore <https://github.com/donsalvatore> reportou isto
> mostrando como exemplo o projeto Agente Comunitário (
> http://spcultura.prefeitura.sp.gov.br/projeto/152) que tem sub-projetos
> com eventos e ele queria que digitando agente comunitário na busca
> principal aparecesse a agenda de todos os subprojetos, como acontece na
> agenda da single do próprio projeto)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hacklabr/mapasculturais/issues/687>.
>



-- 
Miguel de Castro Perez
http://about.me/migueldecastro
@serra_lheria
cel.: +55 11 97161 2502
