### ISSUE TITLE
TEXTO CURTO LIMITE DE CARACTERES AVISO

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#696]
Miguel,

Coloquei a sinopse de um filme em descrição curta e quando fui salvar ele me avisou que estava com mais de 400 caracteres.
Editei o texto e salvei novamente com menos caracteres, só que, quando ele salva (aparece o ícone de edição salva), ao mesmo tempo não some o aviso de diminuição de caracteres. Ele avisa que você editou mas não some o aviso. Mando print.
![bugcaracteres](https://cloud.githubusercontent.com/assets/2921891/6760532/411244da-cf28-11e4-8b41-902438f4e14c.jpg)

**Comment by marylly** [comment]
@ariadnemelo, poderia testar esta situação por gentileza?

**Comment by ariadnemelo** [comment]
a mensagem de erro foi retirada e o texto é cortado automaticamente pelo `max-lenght` da textarea, acredito que está resolvida
