### ISSUE TITLE
BUG na ocorrência "data invalida"

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#697]
Aquele problema de gerar ocorrências continua.
Estou cadastrando um evento que acontece em vários dias e horários. Como o campo de serviço é editável, estou colocando a primeira e a última data e no campo editável coloco no formato que utilizamos aqui na assessoria. No entanto, ele gera Invalid date. Verifiquei e a busca encontra o evento na data certa, aparece tudo certinho, mas na hora do cadastro fica aparecendo essa data inválida. Você pode verificar isso por favor?

![buginvalid](https://cloud.githubusercontent.com/assets/2921891/6760701/2668fd52-cf2a-11e4-98cc-9cfb3624ec3a.jpg)

**Comment by marylly** [comment]
@ariadnemelo você consegue testar isso, por gentileza? Fica dentro do evento as ocorrências.

**Comment by ariadnemelo** [comment]
@marylly criei um novo evento mas quando eu clico para adicionar uma ocorrência não acontece nada, nem mesmo dá mensagem de erro console. alguma idéia do que possa ser?

**Comment by marylly** [comment]
Acabei de testar, está exibindo a data corretamente e não o texto "Invalid Date". Estou encerrando @ariadnemelo
