### ISSUE TITLE
RH7 installation howto

### ISSUE THREAD

**Issue by crenanlouzada** [hacklabr/mapasculturais#700]

**Comment by crenanlouzada** [comment]
Por favor, tenho um ambiente RH7 com apache + php-fpm (com todas as extensões habilitados) mais um SGBD postgresql com postgis 2.1.

Segue as primeiras perguntas:
1 - Aonde é configurado, dentro da aplicação, a string de conexão, dado que o banco de dados reside num servidor separado?

2 - Qual a raiz propriamente do site? Começa no /src para baixo? Está correto enxergarmos isto a partir da raiz do site?
[root@sildes0860 PRMCRS]# ls -la htdocs/
total 1068
drwxr-xr-x. 5 USRAPAMCRS apache    4096 Apr 13 16:14 .
drwxr-xr-x. 5 USRAPAMCRS apache      56 Feb  4 10:49 ..
drwxrwxr-x. 2 USRAPAMCRS apache       6 Apr 13 16:14 assets
-rwxr-xr-x. 1 USRAPAMCRS apache 1074598 Mar 19 19:00 composer.phar
drwxrwxr-x. 2 USRAPAMCRS apache       6 Apr 13 16:13 files
lrwxrwxrwx. 1 USRAPAMCRS apache      63 Feb  3 16:19 geojson -> protected/application/lib/postgis-restful-web-service-framework
-rw-r--r--. 1 USRAPAMCRS apache      98 Feb  3 16:19 index.php
drwxr-xr-x. 4 USRAPAMCRS apache    4096 Feb  3 16:19 protected
-rw-r--r--. 1 USRAPAMCRS apache     975 Feb  3 16:19 router.php

3 - Partindo passo a passo do script de configuração de instalação 'install.sh' tudo funcionou corretamente, acertando evidentemente o servidor remoto de banco e as credenciais, exceto a linha
'./db-update.sh'.

4 - Partindo passo a passo do script de configuração 'initial-configuration.sh' tudo funcionou corretamente exceto a linha (generate-proxies.sh): REQUEST_METHOD='CLI' REMOTE_ADDR='127.0.0.1' REQUEST_URI='/' SERVER_NAME=127.0.0.1 SERVER_PORT="8000" ./doctrine orm:generate-proxies
[root@sildes0860 protected]# php ./tools/doctrine.php orm:generate-proxies
PHP Fatal error:  Class 'Symfony\Component\Console\Helper\HelperSet' not found in /var/httpd/procergs/PRMCRS/htdocs/protected/tools/doctrine.php on line 41

5 - Ao tentar abrir o site recebo a informação, e de fato o arquivo 'autoload.php' não existe abaixo do /src.
Warning: require_once(/var/httpd/procergs/PRMCRS/htdocs/protected/application/../vendor/autoload.php): failed to open stream: No such file or directory in /var/httpd/procergs/PRMCRS/htdocs/protected/application/bootstrap.php on line 12

Fatal error: require_once(): Failed opening required '/var/httpd/procergs/PRMCRS/htdocs/protected/application/../vendor/autoload.php' (include_path='.:/var/httpd/procergs/frameworks:/usr/share/php') in /var/httpd/procergs/PRMCRS/htdocs/protected/application/bootstrap.php on line 12

**Comment by uira** [comment]
+1

**Comment by rafaelchavesfreitas** [comment]
**1 -** Você deve fazer a configuração do banco de dados no arquivo de configuração (**protected/application/conf/config.php**) adicionando as linhas abaixo modificadas conforme suas necessidades. 
```PHP
    'doctrine.database' => array(
        'dbname'    => 'mapasculturais',
        'user'      => 'mapasculturais',
        'password'  => 'mapasculturais',
        'host'      => 'localhost',
    ),
```

**2 -** Sim, está correto! a raíz do site é a pasta src do projeto.

**3 -** ver abaixo

**4 -** Aparentemente houve algum problema ao executar o **composer.phar update**, pois é ele que instala todas as bibliotecas. Certifique-se que você tem o **composer.phar** num dos diretórios do **PATH** (conforme descrito em nossos requisitos para a instalação da página inicial do repositório, pode ser a **/usr/local/bin/composer**) e, como você já criou o banco de dados e as fez as configurações iniciais (nos dois casos o problema aconteceu na última linha dos scripts), você pode executar o script **scripts/deploy.sh**, que executará as linhas que não foram executadas.

**5 -** Tem relação com o composer também, poi ele é quem gera o arquivo autoload.php

@crenanlouzada Por favor nos dê retorno de se os problemas foram solucionados e se puder contribuir com o que mais foi feito, se o RH7 não tem alguma versão de software requerida, como foi feito para instalá-las, etc, para que possamos a partir desta issue criar um manual de instalação no RH7.

**Comment by crenanlouzada** [comment]
Olá Rafael,

já avançamos bastante com a string do banco mais o composer, contudo estou
parando no doctrine. Segue:

[root@sildes0860 protected]# HTTP_HOST="localhost" REQUEST_METHOD='CLI'
REMOTE_ADDR='127.0.0.1' REQUEST_URI='/' SERVER_NAME=127.0.0.1
SERVER_PORT="8000" php ./tools/doctrine orm:generate-proxies



  [InvalidArgumentException]
  The helper "em" is not defined.



orm:generate-proxies [--filter="..."] [dest-path]


--
Renan

Em 22 de abril de 2015 21:28, rafaelchavesfreitas <notifications@github.com>
escreveu:

**Comment by crenanlouzada** [comment]
Rafael,

está quase lá. Instalei o autoprefixer via npm e terminei de compilar os
css conforme frisa no compile-sass.sh (deploy.sh). Entretanto quando vou
acessar pela WEB recebo o seguinte:

$ curl  -X GET -I mcrs.des.procergs.reders/index.php
HTTP/1.1 500 Internal Server Error
Date: Thu, 23 Apr 2015 22:08:13 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0,
pre-check=0
Pragma: no-cache
Set-Cookie: PHPSESSID=ve4ljtghvsgqot0s94n4bcj8n1; path=/
Set-Cookie: mapasculturais.uid=0; path=/
Set-Cookie: mapasculturais.adm=deleted; expires=Thu, 01-Jan-1970 00:00:01
GMT; path=/
Content-Length: 0
Connection: close
Content-Type: text/html;charset=UTF-8


Do ponto de vista do server, log de acesso:
172.28.10.252 - - [23/Apr/2015:19:08:13 -0300] "GET /index.php HTTP/1.1"
500 - "-" "curl/7.16.3 (powerpc-apple-darwin9.0) libcurl/7.16.3
OpenSSL/0.9.7l zlib/1.2.3" "" 0 28642 127646 mcrs.des.procergs.reders


ps. Não tenho nada logado no log de erro do apache.

--
Renan


Em 23 de abril de 2015 15:38, Carlos Renan Schick Louzada <
crenan.louzada@gmail.com> escreveu:

**Comment by crenanlouzada** [comment]
Após a instalacao e a configuração inicial ter funcionado, algums URIs do site não funcionam. Por exemplo: painel e busca. Alias, quando clicamos em 'login' na parte da administração, nada acontece.

**Comment by rafaelchavesfreitas** [comment]
@crenanlouzada,

Você está usando Apache, certo? 

Verifique se o mod_rewrite está habilitado.

**Comment by crenanlouzada** [comment]
Sim, está habilitado.

**Comment by crenanlouzada** [comment]
Após a colocação do trecho com as devidas credenciais estou recebendo o seguinte erro.

'app.siteName' => 'CulturaRS',
'app.siteDescription' => 'Cultura RS é a plataforma livre, gratuita e colaborativa de mapeamento da Secretaria da Cultura do Rio Grande do Sul.',

'namespaces' => array_merge( $config['namespaces'], array($active_theme => THEMES_PATH . 'RS') ),
'themes.active' => 'RS',

'maps.includeGoogleLayers' => true,
'app.geoDivisionsHierarchy' => array(
),
'maps.center' => array(-30.012030680358613, -53.1463623046875), // RS
'maps.zoom.default' => 7,


'auth.provider' => 'OpauthLoginCidadao',
'auth.config' => array(
    'client_id' => 'FALAR COM O PESSOAL DO LOGIN CIDADÃO',
    'client_secret' => 'FALAR COM O PESSOAL DO LOGIN CIDADÃO'
),

########################################################################
Parse error: syntax error, unexpected ''client_id'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /var/httpd/procergs/PRMCRS/htdocs/protected/application/conf/config.php on line 95

**Comment by leandrodb** [comment]
@crenanlouzada Para resultar nesse parse error deve ter faltado ou sobrado um parêntese, uma vírgula ou umas aspas no seu config.php

**Comment by crenanlouzada** [comment]
Outra coisa importante para quem utiliza ainda o apache. Na raiz do site precisamos encaminhar todas as rotas (URIs) para o index.php. Assim criamos o .htaccess com o seguinte conteúdo:

RewriteEngine  on
RewriteBase     /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule "(.*)" "index.php?$1" [PT,QSA]

**Comment by crenanlouzada** [comment]
Outra coisa importante para quem utiliza ainda o apache. Na raiz do site precisamos encaminhar todas as rotas (URIs) para o index.php. Assim criamos o .htaccess com o seguinte conteúdo:

RewriteEngine  on
RewriteBase     /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule "(.*)" "index.php?$1" [PT,QSA]
