### ISSUE TITLE
perda da senha e do acesso ao mail da senha

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#705]
"Boa tarde, Don.

Fiz meu cadastro na plataforma SPCultura, e esqueci login e senha, só que agora não consigo recuperar a senha pq não tenho mais acesso ao email utilizado para fazer o cadastro na época.
Preciso do ID para inserir novas informações referente as atividades do nosso grupo no projeto Redes e Ruas. Também tinha cadastrado outros grupos com meu ID e agora preciso ceder a propriedade para eles. Como podemos proceder? Espero que possa me ajudar.
## Abraço

Hércules Laino"

"Boa pergunta.

copio a Luísa e a Keroly para qie tenham ciência desta (im)possibilidade.

Vamos lá.
Perder o acesso do seu mail é ainda pior que a senha do spcultura. rs!
Não existe um método desenvolvido para isso, então o que vai rolar é o método "por favor programador faz essa."

Preciso do link do seu usuário... aí resolvemos, mas nunca sei se de imediato. Vc me cobre caso demore mais de 2 dias, e pode apurrinhar mesmo, ok?

Cadastramos tb uma issue no github sobre este caso para dar poderes à SMC de poder resetar senhas se solicitado... mas ainda o problemas resistirá... como provar que vc é vc, no caso de outros perderem a senha tb, sem burocracia?....

valeu!"

**Comment by rafaelchavesfreitas** [comment]
do projeto https://github.com/hacklabr/mapasculturais-openid
