### ISSUE TITLE
Bug inscrições nos editais :: não encerra período de inscriç∫ao automaticamente e aba de inscritos desaparece

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#712]
segue mail recebi com os comentários da Luciana Piazzon

1) As inscrições não são desativadas automaticamente? Isto é, se o período de inscrições vai até 00h de tal dia, o sistema não bloqueia automaticamente? Acabo de verificar e aparentemente a inscrição online continuava ativada, então desativei.

2) Ao desativar (uma vez que não funcionou automaticamente) as inscrições online, a aba inscritos deixa de aparecer para mim - nesse caso, faria muito sentido que ela continuasse aparecendo, já que preciso visualizar essas informações exatamente quando se encerram as inscrições... (e, por outro lado, se mantenho ativada, as pessoas podem continuar se inscrevendo)

Enfim, é isso mesmo?
Se for, podemos incluir esses itens nos ajustes a serem feitos?

Abs,
L

**Comment by rafaelchavesfreitas** [comment]
o bug não existe, referente a #654
