### ISSUE TITLE
PERDA DE SENHA :: o sistema não devolve para yahoo

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#717]
Pessoas que perdem a senah e requerem uma nova não recebem o mail caso seja yahoo

**Comment by marylly** [comment]
@donsalvatore talvez seja uma pergunta idiota, mas será que não foi para pasta de e-mails indesejados ou coisas do tipo?

**Comment by rafaelchavesfreitas** [comment]
do projeto https://github.com/hacklabr/mapasculturais-openid
