### ISSUE TITLE
Módulo de inscrições travar por quantidade de inscritos

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#722]
Em caso de oficina ou curso, tem como limitar a quantidade geral de inscrição? Ou seja, ir até o limite de vagas disponivel?
Exemplo> vou fazer um oficina é tenho 40 vagas disponiveis. Tem como via plataforma receber somente as 40 primeiras inscrições
?

boa demanda de SOBRAL

**Comment by rafaelchavesfreitas** [comment]
mesmo que #884
