### ISSUE TITLE
Aplicação falha silenciosamente

### ISSUE THREAD

**Issue by guilhermednt** [hacklabr/mapasculturais#729]
Temos uma instalação em um servidor de testes e eu possuo uma instalação local.
A princípio, ambas compartilham o mesmo código, banco de dados e arquivos de configuração.

Problema: apenas no servidor de testes, na aba Agentes, por exemplo, não são exibidos dados.

Monitorando a rede podemos ver que a requisição `GET /api/agent/find/?&@select=id,name,location&@order=name%20ASC` recebe a seguinte resposta:

``` json
{
    "error": true,
    "data": "property api\/agent\/find\/ does not exists"
}
```

O problema não parece ser com a conexão ao banco uma vez que na página inicial a contagem de agentes é exibida corretamente.

Na minha instalação local o problema não ocorre. Alguma dica de como posso encontrar a origem desse problema?

Além disso, seria interessante adicionar o erro ao log pois isso não está acontecendo, o que deixa tanto o usuário quanto o programador "no escuro".

**Comment by rafaelchavesfreitas** [comment]
@guilhermednt vocês estão usando apache + php-fpm, apache + mod_php ou nginx + php-fpm?

Me parece que o caminho (api/agent/find) está sendo adicionada à query string.

Pode verificar?

**Comment by rafaelchavesfreitas** [comment]
http://docs.slimframework.com/routing/rewrite/

**Comment by guilhermednt** [comment]
Resolvido! Era isso mesmo, @rafaelchavesfreitas. Por algum motivo o .htaccess não foi junto quando enviei o código ao servidor, então estava desatualizado e errado. :)
