### ISSUE TITLE
Painel :: ao ceder ou transferir propriedade manter histórico do que foi publicado pelo agente

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#733]
demanda da SMC por avaliar que muitos gestores e monitores que contribuem com as informações na plataforma vêem no painel que não possuem eventos, ou projetos. ao ceder as singles o número zera o que indica que vc não fez nada na plataforma.

Importância do histórico de contribuição

**Comment by marylly** [comment]
Agente
1. Criação de 1ª versão do histórico:
- [ ] Tipo de agente;
- [ ] Nome exibição;
- [ ] Descrição curta;
- [ ] Site;
- [ ] Nome;
- [ ] CPF/CNPJ;
- [ ] Data de Nascimento/Criação;
- [ ] Gênero;
- [ ] Orientação Sexual;
- [ ] Raça/Cor;
- [ ] Email Privado;
- [ ] Email;
- [ ] Telefone Público;
- [ ] Telefone 1;
- [ ] Telefone 2;
- [ ] Endereço;
- [ ] CEP;
- [ ] Logradouro;
- [ ] Número;
- [ ] Complemento;
- [ ] Bairro;
- [ ] Município;
- [ ] Estado;
- [ ] Localização;
- [ ] Descrição Longa;
- [ ] Área de Atuação;
- [ ] Tags;
- [ ] Links;

2. Atualização e geração da 2ª versão do histórico:
- [ ] Agentes Relacionados
- [ ] Selo Relacionados

3. Atualização de campos e relacionamentos, gerando a 3ª versão do histórico;
