### ISSUE TITLE
PROJETOS: oferecer mais de uma possibilidade de inserir categorias editáveis (checkbox)

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#737]
um dos grandes impedimentos de alguns departamentos não utilizarem o módulo de editais.

**Comment by marylly** [comment]
@donsalvatore poderia explicar melhor a situação?

**Comment by rafaelchavesfreitas** [comment]
já foi resolvido com o desenvolvimento dos campos personalizaveis dos editais
