### ISSUE TITLE
Possibilidade de salvar as entidades como rascunho

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [hacklabr/mapasculturais#740]

**Comment by donsalvatore** [comment]
perfeito.
única questão antes de aprovar

mas se tiver 1000 eventos que faço? 1 por 1, vai rolar um check box e tb o botão publicar tudo?
pq apenas a opção de publicar tudo pode trazer problemas caso vc tenha eventos no meio que não queira publicar.

**Comment by donsalvatore** [comment]
outro ponto.
o botão tornar rascunho não poderia figuarar na single de cada entidade? se não, no painel tb ter o botão para "tornar selecionados dm rascunho". pq a rotina de publicar um evento e depois ter de recorrer ao painel para fazer a ação gera cliques e telas desneceesárias.

**Comment by donsalvatore** [comment]
aqui ficou uam questão. gerou confusão o botão salvar e publicar. se puder o nome do botão deve ser SALVAR COMO RASCUNHO (pq aquele box que aparece e nada) eo outro botão PUBLICAR. parece bobagem mas os antigos usuários vão se confundir pacas
