### ISSUE TITLE
Publicar todos os eventos de um mesmo projeto de uma só vez.

### ISSUE THREAD

**Issue by rafaelchavesfreitas** [hacklabr/mapasculturais#741]

**Comment by donsalvatore** [comment]
obs.; aqui já saiu a conversa da importância do checkbox além da opção publicar tudo de um projeto. É postergar um problema que jeca cantaram aqui a bola.

**Comment by donsalvatore** [comment]
opa!!! tá funcionando mas não coloquei no "done" pq no firefox tá respondendo esquesito. Trava, demora, enfim... estranho. Vale a pena conferir. Tb botei no failed pq o design tá estranho referente a issue https://github.com/hacklabr/mapasculturais/issues/752
