### ISSUE TITLE
Apagar Agente

### ISSUE THREAD

**Issue by uira** [hacklabr/mapasculturais#743]
@rafaelchavesfreitas 

> Entendi. É o seguinte: não se apaga o agente padrão do usuário. Também acho ruim. Acho que o super admin, pelo menos, deveria poder. Posso implementar, não é difícil... Mas implica em apagar tudo que for relacionado com o usuário... Espaços, eventos, projetos.... E isso vai em cascata
> Por não chegarmos a uma conclusão quando pensamos a respeito deixamos assim. A princípio não era possui excluir nada, só colocar na lixeira.

@uira

> Uai, quando deleta tem que escolher um user pra herdar as coisas
> Tem três Uiras Poras, e eu só consigo apagar o perfil q está mais completo
> E tem q ver, pq a gente criou muuuita coisa via importação. Poder deletar ou mesclar perfis, é fundamental

**Comment by Andreqlp** [comment]
+1
