### ISSUE TITLE
SINGLE PROJETO ABA DE STATUS DO EVENTO botões desalinhados

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#752]
![untitled11](https://cloud.githubusercontent.com/assets/2921891/7899202/234030d8-06f1-11e5-8d7d-8093487844c5.jpg)

**Comment by marylly** [comment]
@ariadnemelo poderia avaliar este item, por gentileza.

**Comment by ariadnemelo** [comment]
já foi corrigido
