### ISSUE TITLE
Abas agendas ao carregar eventos gera erro de script no FIREFOX

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#761]
![spculturascript](https://cloud.githubusercontent.com/assets/2921891/8222342/624609c6-1540-11e5-9e20-3bcbdeb05bde.jpg)

**Comment by marylly** [comment]
@ariadnemelo faz um teste no firefox por gentileza?

**Comment by ariadnemelo** [comment]
@marylly aparentemente foi corrigido, estou fechando
