### ISSUE TITLE
Bug ao listar espaços culturais

### ISSUE THREAD

**Issue by arakenlotufo** [hacklabr/mapasculturais#778]
Ao mandar listar os espaços e selecionar o tipo de exibição com o lista se clicarmos na foto do espaço e não no nome que a descreve ele redireciona para a lista de agentes e não para o espaço selecionado

**Comment by marylly** [comment]
@arakenlotufo poderia nos mandar um exemplo com imagens ou um vídeo, porque não ficou claro.

**Comment by rafaelchavesfreitas** [comment]
não consegui reproduzir
