### ISSUE TITLE
Erro ao tentar acessar "Meus Espaços" e "Meus Eventos" no painel

### ISSUE THREAD

**Issue by avaloni** [hacklabr/mapasculturais#780]
Acessar o painel e depois em "Meus Espaços" ou "Meus Eventos" a aplicação encontra um erro, segue log.

***
>The application could not run because of the following error:
Details
Type: ErrorException
Code: 2
Message: include(.php): failed to open stream: No such file or directory
File: /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php
Line: 338
>Trace
#0 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(338): Slim\Slim::handleErrors(2, 'include(.php): ...', '/srv/mapas/mapa...', 338, Array)
#1 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(338): MapasCulturais\Theme::partialRender()
#2 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(365): MapasCulturais\Theme->partialRender('panel-search', Array, true)
#3 /srv/mapas/mapasculturais/src/protected/application/themes/BaseV1/views/panel/spaces.php(16): MapasCulturais\Theme->part('panel-search', Array)
#4 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(338): include('/srv/mapas/mapa...')
#5 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(258): MapasCulturais\Theme->partialRender('panel/spaces', Object(Slim\Helper\Set))
#6 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Theme.php(208): MapasCulturais\Theme->fullRender('panel/spaces')
#7 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/View.php(255): MapasCulturais\Theme->render('panel/spaces', NULL)
#8 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/View.php(243): Slim\View->fetch('panel/spaces', NULL)
#9 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(757): Slim\View->display('panel/spaces')
#10 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Controller.php(294): Slim\Slim->render('panel/spaces', Array)
#11 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Controllers/Panel.php(143): MapasCulturais\Controller->render('spaces', Array)
#12 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Controllers/Panel.php(158): MapasCulturais\Controllers\Panel->renderList('spaces', 'space', 'name,type,statu...')
#13 [internal function]: MapasCulturais\Controllers\Panel->GET_spaces()
#14 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Controller.php(270): call_user_func_array(Array, Array)
#15 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(169): MapasCulturais\Controller->callAction('GET', 'spaces', Array)
#16 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/RoutesManager.php(107): MapasCulturais\RoutesManager->callAction(Object(MapasCulturais\Controllers\Panel), 'spaces', Array, false)
#17 [internal function]: MapasCulturais\RoutesManager->MapasCulturais\{closure}(Array)
#18 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#19 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#20 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#21 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#22 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Middlewares/ErrorHandler.php(31): Slim\Middleware\MethodOverride->call()
#23 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/Middlewares/ExecutionTime.php(44): MapasCulturais\Middlewares\ErrorHandler->call()
#24 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): MapasCulturais\Middlewares\ExecutionTime->call()
#25 /srv/mapas/mapasculturais/src/protected/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#26 /srv/mapas/mapasculturais/src/protected/application/lib/MapasCulturais/App.php(397): Slim\Slim->run()
#27 /srv/mapas/mapasculturais/src/index.php(4): MapasCulturais\App->run()
#28 {main}

Pelo que eu entendi, ele procura um 'panel-search' dentro das pastas de parts e não encontra.

**Comment by wagnertw** [comment]
Também confirmo erro.

**Comment by rafaelchavesfreitas** [comment]
resolvido!
