### ISSUE TITLE
Erro ao tentar fazer a inscrição

### ISSUE THREAD

**Issue by Andreqlp** [hacklabr/mapasculturais#790]
A nova janela  ( http://mapa.cultura.ce.gov.br/inscricao/3602648/ )após selecionar o candidato da inscrição foi a seguinte:

**Error**
A website error has occurred. The website administrator has been notified of the issue. Sorry for the temporary inconvenience.

Página do projeto: http://mapa.cultura.ce.gov.br/projeto/36

**Comment by Andreqlp** [comment]
Resolvido!

Um dos campos estava sem a indicação do tipo de pergunta e quando tentava preencher a inscrição aparecia o erro relatado anteriormente.

**Comment by rafaelchavesfreitas** [comment]
o envio de inscrição ainda não estava completamente implementado com as novas opções de configuração de campos. tentar novamente.

**Comment by marylly** [comment]
@Andreqlp este problema ainda persiste ou foi realmente resolvido? Poderia avaliar e nos dar um retorno, por gentileza?

**Comment by Andreqlp** [comment]
@marylly , não lembro desse problema ter aparecido novamente, então acho que foi definitivamente exterminado  :)

**Comment by marylly** [comment]
@Andreqlp, estou encerrando então! Obrigada! =]
