### ISSUE TITLE
Opção para definir tamanho máximo e mínimo de caracteres no campo de texto (textarea)

### ISSUE THREAD

**Issue by Andreqlp** [hacklabr/mapasculturais#791]
Algumas perguntas do edital delimitam o tamanho do texto que deve ser escrito. A exemplo da descrição do projeto que deve ter entre 1500 a 4500 caracteres. Assim, seria viável inserir as opções para inserir a quantidade mínima e máxima no campo de texto (textare)?

![texto minimo e maximo caracteres](https://cloud.githubusercontent.com/assets/14170372/14900469/0df5cd50-0d67-11e6-8f38-4a319bb1ced5.jpg)

**Comment by marylly** [comment]
@Andreqlp agora o campo de definição das opções está ilimitado, correção feita quando foram necessárias incluir novas opções em campos já existentes num edital. Poderia verificar e me atualizar sobre esta correção, por gentileza?

**Comment by Andreqlp** [comment]
@marylly o que você me disse está  funcionando corretamente. Arrochamos o nó e colocamos num campo de múltipla escolha 184 opções com o nome dos municípios do Ceará. 

Agora essa issue diz respeito a uma outra questão, que é a possibilidade  de configurar a quantidade máxima e mínima de caracteres  que deve ter numa resposta do tipo texto.
