### ISSUE TITLE
Alterar a descrição do campo "Agente responsável pela inscrição".

### ISSUE THREAD

**Issue by Andreqlp** [hacklabr/mapasculturais#792]
Não é mais obrigatório inserir a "Raça/Cor" e "Gênero" no perfil do agente para validar a inscrição. Desse modo, o texto do agente responsável pela inscrição pode ser substituído por:

"Agente individual (pessoa física) com os campos CPF, Data de Nascimento/Fundação, Email Privado e Telefone 1 obrigatoriamente preenchidos"

![mudar texto](https://cloud.githubusercontent.com/assets/14170372/14964295/e01339f8-107d-11e6-95b8-778fbe7a84b5.jpg)

**Comment by marylly** [comment]
@ariadnemelo esse eu sei que precisamos avaliar, acredito que não esteja corrigido.
