### ISSUE TITLE
Usabilidade: entidade PROJETO não retorna mensagem de campos em branco ao usuário

### ISSUE THREAD

**Issue by robertkapa** [hacklabr/mapasculturais#808]
Na entidade PROJETOS, quando um usuário se inscreve num edital, ao clicar no botão enviar sem estar com os campos completos, o sistema não indica que existe algum problema em algum campo, e indica que o campo CATEGORIAS tem problemas apesar de não haver. O usuário também deve adivinhar que deve salvar a inscrição para que depois o sistema indique de fato os problemas com a inscrição. 

Recentemente a instalação spcultura passou por esse problema com os usuário na inscrição do edital spcine. Foi feito um vídeo para orientar os usuários: https://www.youtube.com/watch?v=3Y414xdBrME

Sugestão de resolução: rever o fluxo do preenchimento de um PROJETO e inserir validações/mensagens aos usuários para que os mesmos possam saber quais campos estão em branco.

**Comment by kterva** [comment]
hay que salvar antes de enviar la inscripción

**Comment by fabiobianchiwebdev** [comment]
I anwA #9@$@#@.
Em 15/06/2016 4:41 PM, "leonardo" <notifications@github.com> escreveu:

**Comment by robertkapa** [comment]
https://github.com/culturagovbr/mapasculturais/issues/26
