### ISSUE TITLE
Falha de segurança: Link de projeto redireciona para página crackeada

### ISSUE THREAD

**Issue by geciola** [hacklabr/mapasculturais#812]
Alguns projetos do Mapa Cultural do Ceará estão cadastrados com um link de redirecionamento para uma página crackeada. Exemplo: http://mapa.cultura.ce.gov.br/projeto/65/

**Comment by robertkapa** [comment]
http://mapa.cultura.ce.gov.br/projeto/65/

Resolvido! @marylly @rafaelchavesfreitas favor fecharem essa issue.

**Comment by robertkapa** [comment]
![screencapture-mapa-cultura-ce-gov-br-projeto-65-1471977565660](https://cloud.githubusercontent.com/assets/641411/17905279/bec975fe-6948-11e6-8307-dcbc170c698d.png)
