### ISSUE TITLE
os campos de endereço. ao estar deslogado eles aparecem em branco

### ISSUE THREAD

**Issue by donsalvatore** [hacklabr/mapasculturais#818]
Opa meu povo.

identifiquei um buguinho, coisa pouca mas que gera uma leitura equivocada as vezes, coisa que vi na formação.

http://mapa.cultura.df.gov.br/espaco/30/
Apesar do endereço constar os campos ficam em branco (campos: logradouro, número, cep, cidade, etc...)

**Comment by K-Langoso** [comment]
Prezado Don,

Não vi diferenças entre logado e deslogado; esse espaço e outros aparecem para mim da mesma forma.

Está me parecendo mais um erro de preenchimento do responsável pelo espaço.

Por exemplo: http://mapa.cultura.df.gov.br/espaco/50/

Abraços.

**Comment by donsalvatore** [comment]
Opa!

Parece que a questão é por conta de dados importados. Os que assim foram subidos acontece isso. Assim como ha espaços com o pim no mapa sem qualquer endereço (campos) preenchidos.

Abraçone valeu o feed

Miguel de Castro Perez 
+55 11 971612502

**Comment by K-Langoso** [comment]
👍🏼 às ordens!


Em 15 de jul de 2016 10:17 -0300, Miguel Salvatore<notifications@github.com>, escreveu:
