### ISSUE TITLE
Criar opção de limite numério de inscrições em projetos

### ISSUE THREAD

**Issue by robertkapa** [hacklabr/mapasculturais#884]
Na entidade projetos existe a opção "Inscrições". Essa opção possui uma limitação de número de inscrições por usuário (por agente) e por data (data de inicio e fim). No entanto não há limite numérico de vagas. Precisa ser criada uma opção que limite a um determinado número de vagas. 

EX.:

Como funciona hoje:
**Evento - Oficina de teatro**
**Data de inicio:** 01/01/2016
**Data de fim:** 15/01/2016

Quando terminam as incrições? R: apenas no dia 15/01/2016. Não há limite automático de vagas. 

Como deveria operar: 
**Evento - Oficina de teatro**
**Data de inicio:** 01/01/2016
**Data de fim:** 15/01/2016
**Vagas:** 30

Quando terminam as incrições? R: No dia 15/01/2016 ou quando completarem 30 vagas. Nesse caso, se completarem 30 inscrições e ainda estiver dentro do tempo vigente, o sistema deve mostrar um modal ou desabilitar as inscrições.

**Comment by K-Langoso** [comment]
3º caso:

N° de vagas limitadas, mas não o de inscrições, havendo uma seleção posterior.

Atenciosamente,

Ricardo Costa | Departamento de Coordenação dos Centros Culturais | Diretoria de Ação Cultural Regionalizada – DPCC-FMC
Fundação Municipal de Cultura – FMC-PBH | Rua da Bahia, 888 – 11º andar | Centro | BH/MG
Skype/e-mail: ricardocosta@pbh.gov.br | (31) 3277-4859 | 3277-4265 | 984-241-058 | www.pbh.gov.br

(enviado do celular)
<hr>

Em 16 de ago de 2016 17:13 -0300, Robert Kapa <notifications@github.com>, escreveu:

**Comment by robertkapa** [comment]
https://github.com/culturagovbr/mapasculturais/issues/30

**Comment by marylly** [comment]
[ ]- Apesar do limite de inscritos informada, é permitido enviar a inscrição e aprovar.

**Comment by AnnaNee** [comment]
@marylly corrigido para aprovar e realizar novas inscrições

**Comment by marylly** [comment]
@robertkapa poderiam testar, por gentileza?
