### ISSUE TITLE
O sistema deve calcular quanto tempo um determinado cadastro das entidades agente e espaço foi criado. Se Espaço e/ou agente tiverem sido criados há mais de 4 meses e não houver qualquer tipo de atualização, o sistema deve mandar um EMAIL para o agente, sugerindo que o cadastro seja atualizado.

### ISSUE THREAD

**Issue by marylly** [hacklabr/mapasculturais#916]
Verificar a funcionalidade de envio de e-mail na branch https://github.com/hacklabr/mapasculturais/tree/devel-mailer

**Comment by leogermani** [comment]
Pra isso seria legal que tivesse uma configuração pra escolher a partir de qto tempo a info é considerada velha e manda email...

e tb pra decidir se o mapa deixa de exibir os velhos nos resultados da busca ou não...

e aí tem q ter um jeito de poder ver quais são os velhos... 

enfim, acho que é só uma sinaliação de q essa tarefa envolve outras

**Comment by marylly** [comment]
@leogermani isso está pronto em homologação pela LaFabbrica
Segue a documentação: https://github.com/hacklabr/mapasculturais/blob/master/documentation/docs/mc_config_plugins.md#notificações
