### ISSUE TITLE
Mudar nomenclatura de inserção de agentes responsáveis na entidade Eventos e Espaços

### ISSUE THREAD

**Issue by robertkapa** [hacklabr/mapasculturais#960]
Essa issue é para facilitar o entendimento de atribuição de responsável. 

![selecao_033](https://cloud.githubusercontent.com/assets/641411/19169665/d79bee84-8beb-11e6-83a2-f8e0ef0a737a.png)

![selecao_034](https://cloud.githubusercontent.com/assets/641411/19169668/dc6dfc72-8beb-11e6-9538-05a1f3cba936.png)

**Comment by marylly** [comment]
Alterar para "Agentes Relacionados" @ariadnemelo
